import Mathlib.Tactic.Basic

register_simp_attr keccak_constants

register_simp_attr target_part_sizes_known
register_simp_attr word_parts_known
register_simp_attr to_absorb
register_simp_attr to_cell_manager
register_simp_attr to_decode
register_simp_attr to_iota_s
register_simp_attr to_os
register_simp_attr to_s
